### PR TITLE
graphiql + /idl

### PR DESCRIPTION
**Pull request by sgratzl**
add option to get the scheme via `/graphql/idl`

integrate GraphiQL and made it accessible via `/graphql/ui/`

to build and update the static website run

```
cd public
npm install
npm run build
```

### CODE REVIEW

**Comment by jexp** [comment]
Samuel thanks a lot. I think the endpoint makes sense but think that integrating graphiql goes beyond the scope of the extension. 

So if you ca limit the pr to the former that would be great. 

Also please sign our cla 
https://neo4j.com/developer/cla/

**Comment by sgratzl** [comment]
btw. I extracted the UI part to an own plugin -> https://github.com/sgratzl/neo4j-graphiql-plugin

**Comment by jexp** [comment]
Cool, thanks a lot.
Do you want to write a short article about it? for blog.grandstack.io ?

Or even better what do you think about wrapping this up as a graph app for Neo4j desktop?
See: https://github.com/neo4j-apps/graph-app-starter
Then it should be easy to install and to keep up to date?

@johnymontana has similar plans for a graph app for schema editing and using the schema either with the server extension or neo4j-graphql-js.

**Comment by jexp** [comment]
May i ask what you use neo4j-graphql for? Would be interesting to see the different usecases.

**Pull request closed without merging**
