### PR TITLE
Fix null

### PR DESCRIPTION
**Pull request by jessitron**
There's a null pointer exception for the suggested queries from graphiql.

This fixes it, and causes it to return results.

/cc @johnsonr

### CODE REVIEW

**Comment by jexp** [comment]
Hey Jessica, 
thanks a lot for your contribution.

Something went wrong with your PR tough. There are a ton of other commits in there :) I try to grab your single commit and apply that manually.

**Comment by jessitron** [comment]
yeah I don't know what happened there! ... something with an automatic fork that github created for an earlier PR on the README probably.

Thanks! yeah, applying that manually is great.

**Comment by jexp** [comment]
Hey @jessitron did you use the release version or did you build it locally?
I'm trying with a recent build but can't reproduce the NPE issue?

graphiql

**Comment by jexp** [comment]
Handled manually. Thanks!

**Pull request closed without merging**
